# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botwallet < Formula
  desc "CLI for AI agents to manage their Botwallet accounts"
  homepage "https://botwallet.co"
  version "0.1.0-beta.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/botwallet-co/agent-cli/releases/download/v0.1.0-beta.3/botwallet_0.1.0-beta.3_darwin_amd64.tar.gz"
      sha256 "7196718b321bb9fafeb5b552c8954a97785f936f2e146b2b014c701bf714ad0a"

      define_method(:install) do
        bin.install "botwallet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/botwallet-co/agent-cli/releases/download/v0.1.0-beta.3/botwallet_0.1.0-beta.3_darwin_arm64.tar.gz"
      sha256 "7a1b6f2d47cab6f595a250e5db9875364b4cd3f80f132ff7ed01ec671d4838f2"

      define_method(:install) do
        bin.install "botwallet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/botwallet-co/agent-cli/releases/download/v0.1.0-beta.3/botwallet_0.1.0-beta.3_linux_amd64.tar.gz"
      sha256 "844b1f07a9b48902459ef3a46a1254d82716f2437a57db47e113c145edfc8418"
      define_method(:install) do
        bin.install "botwallet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/botwallet-co/agent-cli/releases/download/v0.1.0-beta.3/botwallet_0.1.0-beta.3_linux_arm64.tar.gz"
      sha256 "7c94d61533440c6bf0789262f000c51f4f610d845bcdcd30cf955751b4e87563"
      define_method(:install) do
        bin.install "botwallet"
      end
    end
  end

  test do
    system "#{bin}/botwallet", "version"
  end
end
